name: build

on:
  # Necessary when pull requests are updated.
  push: {}

  # Necessary when pull requests are opened / closed.
  pull_request:
    paths-ignore:
      - '*.md'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.3.4
      - uses: gradle/wrapper-validation-action@v1.0.4

      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: 11

      - run: ./gradlew test
