name: build

on:
  pull_request:
    paths-ignore:
      - '*.md'
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.3.4
      - uses: gradle/wrapper-validation-action@v1.0.4

      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: 11

      - run: ./gradlew test

  publish:
    name: Publish
    if: ${{ github.ref == 'refs/heads/main' && github.repository == 'cashapp/kfactories' }}
    runs-on: ubuntu-latest
    env:
      ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.SONATYPE_NEXUS_USERNAME }}
      ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.SONATYPE_NEXUS_PASSWORD }}
      ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.ARTIFACT_SIGNING_PRIVATE_KEY }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - uses: gradle/wrapper-validation-action@v1.0.4
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: 11

      - name: Assign a version
        run: |
          # set a version name like "2023.05.26.091805-c1fcb3a"
          echo "VERSION_NAME=$(git log -n1 --pretty='format:%cd' --date=format:'%Y.%m.%d.%H%M%S')-$(git rev-parse --short=7 HEAD)" >> gradle.properties
          cat gradle.properties

      - name: Publish the artifacts
        run: |
          gradle clean publish --stacktrace
