name: Publish

on:
  push:
    tags: [ "*" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.3.4
      - uses: gradle/wrapper-validation-action@v1.0.4

      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: 11

      - run: ./gradlew test

  publish:
    name: Publish
    runs-on: ubuntu-latest
    env:
      ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.SONATYPE_NEXUS_USERNAME }}
      ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.SONATYPE_NEXUS_PASSWORD }}
      ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.ARTIFACT_SIGNING_PRIVATE_KEY }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - uses: gradle/wrapper-validation-action@v1.0.4
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: 11

      - name: Assign a version
        run: |
          # set a version based on the tag name.
          echo "VERSION_NAME=$(git describe --tags --abbrev=0)" >> gradle.properties
          cat gradle.properties

      - name: Publish the artifacts
        run: |
          gradle clean publish --stacktrace
